hyperskill_project:
  id: 137
  ide_files: https://stepik.org/media/attachments/lesson/428392/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Thu, 01 Jan 1970 00:00:00 UTC
stages:
- id: 730
  step: 11307
  is_completed: false
- id: 731
  step: 11308
  is_completed: false
- id: 732
  step: 11309
  is_completed: false
- id: 733
  step: 11310
  is_completed: false
- id: 734
  step: 11311
  is_completed: false
topics:
  0:
  - title: Introduction to Node.js
    theory_id: 12691
  - title: IDE
    theory_id: 10996
  - title: Introduction to Operating systems
    theory_id: 9704
  - title: World Wide Web
    theory_id: 6633
  - title: HyperText Transfer Protocol
    theory_id: 6569
  - title: HTTP URL
    theory_id: 6740
  - title: Block-level elements
    theory_id: 7271
  - title: Inline elements
    theory_id: 7518
  - title: Images
    theory_id: 9237
  - title: The lang attribute
    theory_id: 12212
  - title: Command line overview
    theory_id: 8977
  - title: Parameters and Options
    theory_id: 9746
  - title: Web development
    theory_id: 13931
  - title: HTML basics
    theory_id: 6434
  - title: Tags and Attributes
    theory_id: 7536
  - title: HTML page structure
    theory_id: 6491
  - title: Introduction to JavaScript
    theory_id: 8016
  - title: WebStorm
    theory_id: 9492
  1:
  - title: What is CSS
    theory_id: 7678
  - title: HTML attributes id and class
    theory_id: 7527
  - title: Links
    theory_id: 11834
  - title: Intro to Lists
    theory_id: 8178
  2:
  - title: Binary numbers
    theory_id: 5544
  - title: Hexadecimal numbers
    theory_id: 8788
  - title: Interface elements
    theory_id: 15253
  - title: Colors
    theory_id: 14914
  - title: Connecting CSS to HTML
    theory_id: 7418
  - title: Basic syntax
    theory_id: 7722
  - title: Comments
    theory_id: 7730
  - title: Relative units
    theory_id: 10671
  - title: Absolute units
    theory_id: 10605
  - title: CSS Selectors
    theory_id: 7738
  - title: Introduction to Flexbox
    theory_id: 11760
  - title: Orientation and Display order
    theory_id: 11768
  - title: Flexibility, growth and contraction ratio
    theory_id: 18859
  - title: Axis alignment
    theory_id: 11784
  - title: Attribute selectors and Universal selector
    theory_id: 12228
  - title: Combinators
    theory_id: 12236
  - title: Comments
    theory_id: 7502
  - title: Position
    theory_id: 11581
  - title: Float
    theory_id: 12697
  - title: Clear
    theory_id: 12705
  - title: Margin and Padding
    theory_id: 8346
  - title: Positioning properties
    theory_id: 8204
  - title: Width and Height
    theory_id: 8325
  - title: Google Fonts
    theory_id: 7844
  - title: Border
    theory_id: 8355
  - title: Text Alignment
    theory_id: 11589
  - title: line-height
    theory_id: 11153
  - title: List style
    theory_id: 11645
  - title: RGB
    theory_id: 8819
  - title: Colors in CSS
    theory_id: 7973
  - title: z-index
    theory_id: 11161
  - title: Background
    theory_id: 11670
  3:
  - title: Comments
    theory_id: 8170
  - title: Intro to HTML forms
    theory_id: 6560
  - title: Introduction to Animation
    theory_id: 10287
  - title: DOM
    theory_id: 8635
  - title: Connecting JavaScript to HTML
    theory_id: 7510
  - title: Pseudo-classes
    theory_id: 9762
  - title: Naming variables
    theory_id: 8364
  - title: Overview of the basic program
    theory_id: 8154
  - title: Multi-line programs
    theory_id: 8162
  - title: Variables
    theory_id: 8186
  - title: Strings and Numbers
    theory_id: 8194
  - title: Arithmetic operators
    theory_id: 8372
  - title: Functions
    theory_id: 8388
  - title: setTimeout and setInterval
    theory_id: 9680
  - title: Anonymous Function
    theory_id: 10865
  - title: Arrow Functions
    theory_id: 8455
  - title: Opacity
    theory_id: 11169
  - title: JSON
    theory_id: 6854
  - title: Introduction to Objects
    theory_id: 8588
  - title: DOM methods
    theory_id: 8662
  - title: ClassList
    theory_id: 11653
  4:
  - title: Visibility
    theory_id: 10840
  - title: Intro to Tables
    theory_id: 10832
  - title: Introduction to Linux
    theory_id: 9526
  - title: Starting with Git
    theory_id: 10894
